---
title: Partners Template
url: https://basekit-templates.github.io/partners-template
timezone: Europe/London
collections:
  posts:
    title: Posts
    output: true
    is_post: true
    layout: post
  uploads:
    title: Uploads
    output: true
exclude:
- README.md
- LICENSE
gems:
- jekyll-sitemap
permalink: pretty
excerpt_separator: "<!-- more -->"
description: The site builder
avatar: https://avatars0.githubusercontent.com/u/1006602?s=100
avatarurl: https://avatars0.githubusercontent.com/u/1006602
colour: "#383838"
meta:
  facebook: TeamBaseKit
  twitter: BaseKit
sass:
  style: compressed
