# Excluded files
exclude:
- README.md
- LICENSE
- CNAME

# Gems
gems:
- jekyll-sitemap

# Permalinks
permalink: pretty

# Posts
excerpt_separator: <!-- more -->

# Site info
url: "http://basekit.com"
title: "BaseKit"
description: "The site builder"
avatar: "https://www.gravatar.com/avatar/6c0377abcf4da91cdd35dea4554b2a4c?s=300"
avatarurl: "https://avatars0.githubusercontent.com/u/1006602"
colour: "#363636"

# Metadata
meta:
  facebook: TeamBaseKit
  twitter: BaseKit

# Defaults
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      is_page: true
      layout: page
  -
    scope:
      path: ""
      type: posts
    values:
      is_post: true
      layout: post
      icon: article
