---
title: Partners Template
url: http://basekit-templates.github.io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    is_page: true
    layout: page
- scope:
    path: ''
    type: posts
  values:
    is_post: true
    layout: post
    icon: article
exclude:
- README.md
- LICENSE
gems:
- jekyll-sitemap
permalink: pretty
excerpt_separator: "<!-- more -->"
description: The site builder
avatar: https://avatars0.githubusercontent.com/u/1006602?s=100
avatarurl: https://avatars0.githubusercontent.com/u/1006602
colour: "#383838"
meta:
  facebook: TeamBaseKit
  twitter: BaseKit
sass:
  style: compressed
